"""Loader for the community FPL historical archive.

The archive (vaastav/Fantasy-Premier-League) is a season-by-season mirror of the
FPL API's own data, going back further than we could ever collect ourselves. It
gives the project two things the live API cannot:

  * Cross-season history from day one, so "since 2023/24" questions work on the
    day the service launches rather than a year later.
  * Real per-gameweek price and ownership (`value` and `selected` in
    merged_gw.csv), which is genuine point-in-time data at gameweek grain --
    the history tables are populated from it rather than sitting empty until
    enough daily snapshots accumulate.

The archive's schema drifts between seasons: `position` and `team` appear in
merged_gw only from 2020-21, expected-goals columns only from 2022-23, and the
defensive-contribution columns only from 2025-26. Everything here reads by
column *name* and returns None for absent columns rather than zero, because a
zero would make an average over history quietly wrong.
"""

from __future__ import annotations

import csv
import io
import logging
import time
from collections.abc import Iterator
from dataclasses import dataclass
from datetime import UTC, datetime

import httpx

from fplq.config import Settings
from fplq.config import settings as default_settings
from fplq.ingest.store import RawStore, open_store, sha256

log = logging.getLogger(__name__)

NAMESPACE = "fpl_archive"

# Files we pull per season. players_raw is the identity spine (it carries the
# stable cross-season `code`); merged_gw is the fact table; the other two are
# dimensions.
SEASON_FILES = ("players_raw.csv", "teams.csv", "fixtures.csv", "gws/merged_gw.csv")


@dataclass
class ArchiveFile:
    season: str
    filename: str
    rows: list[dict[str, str]]
    raw_uri: str
    content_sha256: str
    fetched_at: datetime
    source_uri: str


# The archive is generated by Python scripts that str() their way to CSV, so
# missing values arrive as the literal strings "None" and "nan" rather than as
# empty fields. Treating those as text is how a birth_date column ends up
# rejecting a row; treating them as zero would be worse. One sentinel set,
# applied by every coercion below.
_NULLS = {"", "none", "nan", "null", "na", "n/a", "-"}


def _blank(value: str | None) -> bool:
    return value is None or value.strip().lower() in _NULLS


def _to_text(value: str | None) -> str | None:
    return None if _blank(value) else value.strip()


def _to_int(value: str | None) -> int | None:
    if _blank(value):
        return None
    try:
        return int(float(value))
    except ValueError:
        return None


def _to_float(value: str | None) -> float | None:
    if _blank(value):
        return None
    try:
        return float(value)
    except ValueError:
        return None


def _to_bool(value: str | None) -> bool | None:
    if _blank(value):
        return None
    return value.strip().lower() in {"true", "1", "t", "yes"}


def _to_ts(value: str | None) -> datetime | None:
    if _blank(value):
        return None
    text = value.strip().replace("Z", "+00:00")
    try:
        parsed = datetime.fromisoformat(text)
    except ValueError:
        return None
    return parsed if parsed.tzinfo else parsed.replace(tzinfo=UTC)


class ArchiveClient:
    """Fetches season CSVs, lands them in the raw store, parses them to dicts."""

    def __init__(self, settings: Settings = default_settings,
                 store: RawStore | None = None,
                 client: httpx.Client | None = None) -> None:
        self.settings = settings
        self.store = store or open_store(settings.raw_store_uri)
        self._client = client or httpx.Client(
            timeout=settings.request_timeout_s,
            headers={"User-Agent": settings.user_agent},
            follow_redirects=True,
        )

    def close(self) -> None:
        self._client.close()

    def __enter__(self) -> ArchiveClient:
        return self

    def __exit__(self, *exc: object) -> None:
        self.close()

    def _get(self, url: str, *, attempts: int = 4) -> bytes:
        """Fetch with backoff.

        The archive files are up to ~6 MB and the CDN will occasionally close a
        connection mid-transfer. Without this, one dropped connection fails a
        whole multi-season load an hour in -- which is exactly what happened the
        first time this ran.
        """
        last: Exception | None = None
        for attempt in range(attempts):
            try:
                response = self._client.get(url)
                response.raise_for_status()
                return response.content
            except (httpx.HTTPError, httpx.TransportError) as exc:
                last = exc
                backoff = 2.0**attempt
                log.warning("GET %s failed (%s); retrying in %.0fs", url, exc, backoff)
                time.sleep(backoff)
        raise RuntimeError(f"GET {url} failed after {attempts} attempts") from last

    def fetch(self, season: str, filename: str) -> ArchiveFile:
        url = f"{self.settings.archive_base}/{season}/{filename}"
        log.info("fetching %s", url)
        body = self._get(url)
        fetched_at = datetime.now(UTC)

        uri = self.store.put_snapshot(
            f"{NAMESPACE}/{season}", filename, body, suffix="csv", when=fetched_at
        )
        # utf-8-sig: several season files carry a BOM, which otherwise turns the
        # first column name into '﻿code' and silently breaks every lookup.
        text = body.decode("utf-8-sig", errors="replace")
        rows = list(csv.DictReader(io.StringIO(text)))
        log.info("  %s/%s -> %d rows", season, filename, len(rows))

        return ArchiveFile(
            season=season,
            filename=filename,
            rows=rows,
            raw_uri=uri,
            content_sha256=sha256(body),
            fetched_at=fetched_at,
            source_uri=url,
        )

    def fetch_season(self, season: str) -> Iterator[ArchiveFile]:
        for filename in SEASON_FILES:
            yield self.fetch(season, filename)


# ---------------------------------------------------------------------------
# Row shaping
#
# These turn the archive's column names into the warehouse's vocabulary. They
# are pure functions over dicts so they can be tested without a network or a
# database, and so a season whose schema drifts is a test case rather than a
# production surprise.
# ---------------------------------------------------------------------------


def parse_player_row(row: dict[str, str]) -> dict[str, object]:
    """A row of players_raw.csv -> the fields identity resolution needs."""
    first = (row.get("first_name") or "").strip()
    second = (row.get("second_name") or "").strip()
    return {
        "fpl_player_code": _to_int(row.get("code")),
        "fpl_element_id": _to_int(row.get("id")),
        "first_name": first or None,
        "last_name": second or None,
        "display_name": (row.get("web_name") or "").strip() or f"{first} {second}".strip(),
        "full_name": f"{first} {second}".strip(),
        "birth_date": _to_text(row.get("birth_date")),
        "position_id": _to_int(row.get("element_type")),
        "fpl_team_id": _to_int(row.get("team")),
        "fpl_team_code": _to_int(row.get("team_code")),
        # now_cost is in tenths of a million: 125 -> 12.5
        "end_price": (lambda c: None if c is None else c / 10.0)(_to_int(row.get("now_cost"))),
        "cost_change_start": _to_int(row.get("cost_change_start")),
        "squad_number": _to_int(row.get("squad_number")),
        "total_points": _to_int(row.get("total_points")),
    }


def start_price_from(parsed: dict[str, object]) -> float | None:
    """Season-opening price, reconstructed from end price and cumulative change.

    The archive stores the final price plus `cost_change_start` (the net change
    in tenths since the season opened), so the opening price is recoverable
    exactly. Worth doing: it is what "was he worth it at the start of the
    season" questions compare against.
    """
    end = parsed.get("end_price")
    change = parsed.get("cost_change_start")
    if end is None or change is None:
        return end  # type: ignore[return-value]
    return round(float(end) - (int(change) / 10.0), 1)


def parse_team_row(row: dict[str, str]) -> dict[str, object]:
    return {
        "fpl_team_id": _to_int(row.get("id")),
        "fpl_team_code": _to_int(row.get("code")),
        "name": _to_text(row.get("name")) or "",
        "short_name": (row.get("short_name") or "").strip(),
        "strength_overall_home": _to_int(row.get("strength_overall_home")),
        "strength_overall_away": _to_int(row.get("strength_overall_away")),
        "strength_attack_home": _to_int(row.get("strength_attack_home")),
        "strength_attack_away": _to_int(row.get("strength_attack_away")),
        "strength_defence_home": _to_int(row.get("strength_defence_home")),
        "strength_defence_away": _to_int(row.get("strength_defence_away")),
    }


def parse_fixture_row(row: dict[str, str]) -> dict[str, object]:
    return {
        "fpl_fixture_id": _to_int(row.get("id")),
        "gameweek_number": _to_int(row.get("event")),
        "kickoff_at": _to_ts(row.get("kickoff_time")),
        "home_fpl_team_id": _to_int(row.get("team_h")),
        "away_fpl_team_id": _to_int(row.get("team_a")),
        "home_score": _to_int(row.get("team_h_score")),
        "away_score": _to_int(row.get("team_a_score")),
        "home_difficulty": _to_int(row.get("team_h_difficulty")),
        "away_difficulty": _to_int(row.get("team_a_difficulty")),
        "is_finished": _to_bool(row.get("finished")) or False,
    }


# Columns that only exist in some seasons. Absent -> None, never 0.
_INT_STATS = (
    "minutes", "starts", "total_points", "goals_scored", "assists",
    "clean_sheets", "goals_conceded", "own_goals", "penalties_saved",
    "penalties_missed", "yellow_cards", "red_cards", "saves", "bonus", "bps",
    "transfers_in", "transfers_out", "tackles", "recoveries",
    "clearances_blocks_interceptions", "defensive_contribution",
)
_FLOAT_STATS = (
    "influence", "creativity", "threat", "ict_index",
    "expected_goals", "expected_assists", "expected_goal_involvements",
    "expected_goals_conceded",
)


def parse_gameweek_row(row: dict[str, str]) -> dict[str, object]:
    """A row of merged_gw.csv -> one player-fixture fact.

    Note `value` and `selected`: the price and ownership that were true at that
    gameweek. This is the point-in-time data, and it is why the archive is worth
    ingesting rather than treating as a nice-to-have.
    """
    parsed: dict[str, object] = {
        "fpl_element_id": _to_int(row.get("element")),
        "name": _to_text(row.get("name")) or "",
        "position_code": _to_text(row.get("position")),
        "team_name": _to_text(row.get("team")),
        "gameweek_number": _to_int(row.get("GW")) or _to_int(row.get("round")),
        "fpl_fixture_id": _to_int(row.get("fixture")),
        "opponent_fpl_team_id": _to_int(row.get("opponent_team")),
        "was_home": _to_bool(row.get("was_home")),
        "kickoff_at": _to_ts(row.get("kickoff_time")),
        "price_at_deadline": (lambda v: None if v is None else v / 10.0)(_to_int(row.get("value"))),
        "selected_at_deadline": _to_int(row.get("selected")),
        "expected_points": _to_float(row.get("xP")),
    }
    for column in _INT_STATS:
        parsed[column] = _to_int(row.get(column))
    for column in _FLOAT_STATS:
        parsed[column] = _to_float(row.get(column))
    return parsed
