"""Command line entry point.

    fplq bootstrap                 create the database, roles and schema
    fplq load --seasons 2024-25    fetch and load seasons from the archive
    fplq ingest                    fetch a live snapshot and refresh the current season
    fplq replay --batch-id 12      re-run a past live ingest from raw.document, no fetch
    fplq issues                    list unresolved identity problems
    fplq stats                     row counts, so a load can be sanity-checked
"""

from __future__ import annotations

import argparse
import logging
import secrets
import sys
from urllib.parse import quote

from fplq.config import ARCHIVE_SEASONS, CURRENT_SEASON, REPO_ROOT, require_dsn, settings

log = logging.getLogger("fplq")


def _provision_credentials() -> dict[str, str]:
    """Return the credentials to use, generating them on first run.

    No password ships in this repository. If the environment does not supply
    one, a random one is generated here and written to .env (gitignored), so a
    fresh clone gets working local credentials that are unique to that machine
    and were never published.

    In deployment the environment is populated from Secrets Manager, nothing is
    missing, and this generates nothing.
    """
    env_path = REPO_ROOT / ".env"
    values = {
        "FPLQ_WRITER_PASSWORD": settings.writer_password,
        "FPLQ_READER_PASSWORD": settings.reader_password,
    }
    generated = [k for k, v in values.items() if not v]
    for key in generated:
        values[key] = secrets.token_urlsafe(24)

    host = "localhost:5432"
    values["FPLQ_WRITER_DSN"] = settings.writer_dsn or (
        f"postgresql://fplq_writer:{quote(values['FPLQ_WRITER_PASSWORD'])}"
        f"@{host}/{settings.database_name}"
    )
    values["FPLQ_READER_DSN"] = settings.reader_dsn or (
        f"postgresql://fplq_reader:{quote(values['FPLQ_READER_PASSWORD'])}"
        f"@{host}/{settings.database_name}"
    )

    if generated:
        existing = env_path.read_text() if env_path.exists() else ""
        lines = [ln for ln in existing.splitlines()
                 if ln.split("=", 1)[0].strip() not in values]
        body = "\n".join(
            [*lines, "", "# Generated by `fplq bootstrap`. Local only; not committed."]
            + [f"{k}={v}" for k, v in values.items()]
        ).strip() + "\n"
        env_path.write_text(body)
        env_path.chmod(0o600)
        log.warning("generated credentials for %s and wrote them to %s",
                    ", ".join(generated), env_path)
    return values


def _bootstrap(_: argparse.Namespace) -> int:
    """Create the cluster-level objects, then apply the schema.

    Order is forced by Postgres: roles are cluster-scoped and must exist before
    a per-database migration can GRANT to them, and CREATE DATABASE cannot run
    inside a transaction. Both happen here, as the admin role, before any
    migration runs.
    """
    import psycopg
    from psycopg import sql
    from psycopg.conninfo import conninfo_to_dict, make_conninfo

    from fplq.db import connect, migrate

    creds = _provision_credentials()

    with psycopg.connect(settings.admin_dsn, autocommit=True) as admin, admin.cursor() as cur:
        for role, password in (
            ("fplq_writer", creds["FPLQ_WRITER_PASSWORD"]),
            ("fplq_reader", creds["FPLQ_READER_PASSWORD"]),
        ):
            cur.execute("SELECT 1 FROM pg_roles WHERE rolname = %s", (role,))
            exists = cur.fetchone() is not None
            statement = sql.SQL("{} {} LOGIN PASSWORD {}").format(
                sql.SQL("ALTER ROLE" if exists else "CREATE ROLE"),
                sql.Identifier(role),
                sql.Literal(password),
            )
            cur.execute(statement)
            log.info("%s role %s", "updated" if exists else "created", role)

        cur.execute("SELECT 1 FROM pg_database WHERE datname = %s", (settings.database_name,))
        if cur.fetchone() is None:
            cur.execute(
                sql.SQL("CREATE DATABASE {} OWNER {}").format(
                    sql.Identifier(settings.database_name), sql.Identifier("fplq_writer")
                )
            )
            log.info("created database %s", settings.database_name)
        else:
            cur.execute(
                sql.SQL("ALTER DATABASE {} OWNER TO {}").format(
                    sql.Identifier(settings.database_name), sql.Identifier("fplq_writer")
                )
            )
            log.info("database %s already exists", settings.database_name)

    # btree_gist backs the exclusion constraint that makes overlapping price
    # history impossible. Creating an extension needs superuser, so it happens
    # here rather than in a migration the writer runs.
    # Re-point the admin DSN at the new database by parsing it, not by string
    # replacement: the earlier `dsn.replace("/postgres?", ...)` silently did
    # nothing for a DSN with no query string, so the extension was created in
    # the wrong database and the migration failed several steps later with a
    # message about gist operator classes.
    admin_params = conninfo_to_dict(settings.admin_dsn)
    admin_params["dbname"] = settings.database_name
    with psycopg.connect(make_conninfo(**admin_params), autocommit=True) as conn, conn.cursor() as cur:
        cur.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # Migrations run as the writer, which owns the database and therefore the
    # schemas. That ownership is what makes the analytics views work for the
    # reader: a view executes with its owner's privileges, so the reader can
    # read through them without any grant on core.
    with connect(creds["FPLQ_WRITER_DSN"]) as conn:
        applied = migrate(conn)
    log.info("applied %d migration(s): %s", len(applied), ", ".join(applied) or "none")

    # Session defaults for the execution role.
    #
    # Be precise about what these are worth. statement_timeout,
    # default_transaction_read_only and search_path are all USERSET parameters:
    # a session can override them with a plain SET, so a query that reaches the
    # database as `SET statement_timeout='1h'; SELECT ...` defeats them. They
    # are sane defaults and a safety net against accident -- they are NOT a
    # boundary against a hostile query.
    #
    # The boundary is the grant: fplq_reader has no privilege on core or raw
    # and no write privilege anywhere, and no SET can change that. What stops
    # the SET from arriving in the first place is the validator in
    # fplq.validate -- single statement, SELECT only, allow-listed schemas and
    # functions, forced LIMIT, EXPLAIN cost gate. These settings sit underneath
    # it as a safety net against accident, which is all they were ever worth.
    with psycopg.connect(settings.admin_dsn, autocommit=True) as admin, admin.cursor() as cur:
        for setting, value in (
            ("statement_timeout", "10s"),
            ("idle_in_transaction_session_timeout", "15s"),
            ("default_transaction_read_only", "on"),
            ("search_path", "analytics"),
        ):
            cur.execute(
                sql.SQL("ALTER ROLE {} SET {} = {}").format(
                    sql.Identifier("fplq_reader"),
                    sql.Identifier(setting),
                    sql.Literal(value),
                )
            )
    log.info("applied session guards to fplq_reader")
    return 0


def _load(args: argparse.Namespace) -> int:
    from fplq.db import connect
    from fplq.transform.loader import load_seasons

    seasons = args.seasons or list(ARCHIVE_SEASONS)
    with connect(require_dsn(settings.writer_dsn, "FPLQ_WRITER_DSN")) as conn:
        reports = load_seasons(conn, seasons)
    for report in reports:
        print(report.summary())
    return 0


def _ingest(args: argparse.Namespace) -> int:
    from fplq.db import connect
    from fplq.transform.live import ingest_live

    with connect(require_dsn(settings.writer_dsn, "FPLQ_WRITER_DSN")) as conn:
        report = ingest_live(conn, args.season)
    print(report.summary())
    # A run that writes nothing is the quiet failure the build log calls out:
    # it looks like success (exit 0, a batch row, no exception) unless
    # something checks the count. A scheduler can alert on this exit code
    # without knowing anything about the pipeline's internals.
    return 1 if report.rows_written == 0 else 0


def _replay(args: argparse.Namespace) -> int:
    from fplq.db import connect
    from fplq.transform.live import replay_batch

    with connect(require_dsn(settings.writer_dsn, "FPLQ_WRITER_DSN")) as conn:
        report = replay_batch(conn, args.batch_id)
    print(report.summary())
    return 0


def _issues(args: argparse.Namespace) -> int:
    from fplq.db import query

    rows = query(
        """
        SELECT issue_type, source, season, raw_value, candidates, detected_at
        FROM core.resolution_issue
        WHERE resolved_at IS NULL
        ORDER BY issue_type, raw_value
        LIMIT %s
        """,
        (args.limit,),
    )
    if not rows:
        print("no open resolution issues")
        return 0
    for row in rows:
        candidates = row["candidates"] or []
        hint = ", ".join(f"{c['name']} ({c['score']:.0f})" for c in candidates[:3])
        print(f"{row['issue_type']:<20} {row['season'] or '-':<9} "
              f"{row['raw_value']:<40} {hint}")
    print(f"\n{len(rows)} open issue(s). Add aliases to {settings.overrides_path}")
    return 0


def _stats(_: argparse.Namespace) -> int:
    from fplq.db import query

    rows = query(
        """
        SELECT 'seasons'      AS entity, count(*) AS n FROM core.season
        UNION ALL SELECT 'teams',          count(*) FROM core.team
        UNION ALL SELECT 'players',        count(*) FROM core.player
        UNION ALL SELECT 'player_seasons', count(*) FROM core.player_season
        UNION ALL SELECT 'gameweeks',      count(*) FROM core.gameweek
        UNION ALL SELECT 'fixtures',       count(*) FROM core.fixture
        UNION ALL SELECT 'player_matches', count(*) FROM core.player_fixture_stat
        UNION ALL SELECT 'price_intervals',count(*) FROM core.player_price_history
        UNION ALL SELECT 'ownership_snaps',count(*) FROM core.player_ownership_snapshot
        UNION ALL SELECT 'open_issues',    count(*) FROM core.resolution_issue
                                           WHERE resolved_at IS NULL
        """
    )
    for row in rows:
        print(f"{row['entity']:<18} {row['n']:>9,}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="fplq", description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("-v", "--verbose", action="store_true")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("bootstrap", help="create database, roles and schema").set_defaults(fn=_bootstrap)

    load = sub.add_parser("load", help="fetch and load seasons from the archive")
    load.add_argument("--seasons", nargs="+", metavar="SEASON",
                      help=f"default: {' '.join(ARCHIVE_SEASONS)}")
    load.set_defaults(fn=_load)

    ingest = sub.add_parser("ingest", help="fetch a live snapshot and refresh the current season")
    ingest.add_argument("--season", default=CURRENT_SEASON)
    ingest.set_defaults(fn=_ingest)

    replay = sub.add_parser("replay", help="re-run a past live ingest from raw.document")
    replay.add_argument("--batch-id", type=int, required=True)
    replay.set_defaults(fn=_replay)

    issues = sub.add_parser("issues", help="list unresolved identity problems")
    issues.add_argument("--limit", type=int, default=50)
    issues.set_defaults(fn=_issues)

    sub.add_parser("stats", help="row counts per table").set_defaults(fn=_stats)

    args = parser.parse_args(argv)
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)-7s %(name)s: %(message)s",
        stream=sys.stderr,
    )
    return args.fn(args)


if __name__ == "__main__":
    raise SystemExit(main())
